try {
    console.log('Start of Try');
    blabla;
    console.log('End of Try');
} catch (error) {
    console.log('Error has occurred');
}